languaje: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy2.7"
 - "pypy3.5"

install:
 - pip install --user codecov
 - pip install --user sklearn
 - pip install --user scipy
 - pip install --user pytest pytest-cov
 - pip install --user .

script:
 - pytest --cov=./

 after_success:
 - codecov